// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, type Options as Options2, type RequestResult, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { ItemsCreateItemData, ItemsCreateItemErrors, ItemsCreateItemResponses, ItemsDeleteItemData, ItemsDeleteItemErrors, ItemsDeleteItemResponses, ItemsReadItemData, ItemsReadItemErrors, ItemsReadItemResponses, ItemsReadItemsData, ItemsReadItemsErrors, ItemsReadItemsResponses, ItemsUpdateItemData, ItemsUpdateItemErrors, ItemsUpdateItemResponses, LoginLoginAccessTokenData, LoginLoginAccessTokenErrors, LoginLoginAccessTokenResponses, LoginLogoutData, LoginLogoutResponses, LoginTestTokenData, LoginTestTokenResponses, PrivateCreateUserData, PrivateCreateUserErrors, PrivateCreateUserResponses, UsersCreateUserData, UsersCreateUserErrors, UsersCreateUserResponses, UsersDeleteUserData, UsersDeleteUserErrors, UsersDeleteUserMeData, UsersDeleteUserMeResponses, UsersDeleteUserResponses, UsersReadUserByIdData, UsersReadUserByIdErrors, UsersReadUserByIdResponses, UsersReadUserMeData, UsersReadUserMeResponses, UsersReadUsersData, UsersReadUsersErrors, UsersReadUsersResponses, UsersRegisterUserData, UsersRegisterUserErrors, UsersRegisterUserResponses, UsersUpdatePasswordMeData, UsersUpdatePasswordMeErrors, UsersUpdatePasswordMeResponses, UsersUpdateUserData, UsersUpdateUserErrors, UsersUpdateUserMeData, UsersUpdateUserMeErrors, UsersUpdateUserMeResponses, UsersUpdateUserResponses, UtilsHealthCheckData, UtilsHealthCheckResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Login Access Token
 *
 * OAuth2 compatible token login, get an access token for future requests
 */
export const loginLoginAccessToken = <ThrowOnError extends boolean = true>(options: Options<LoginLoginAccessTokenData, ThrowOnError>): RequestResult<LoginLoginAccessTokenResponses, LoginLoginAccessTokenErrors, ThrowOnError, 'data'> => (options.client ?? client).post<LoginLoginAccessTokenResponses, LoginLoginAccessTokenErrors, ThrowOnError, 'data'>({
    ...urlSearchParamsBodySerializer,
    responseStyle: 'data',
    url: '/api/v1/login/access-token',
    ...options,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options.headers
    }
});

/**
 * Logout
 *
 * Log out the current user by clearing the access token cookie
 */
export const loginLogout = <ThrowOnError extends boolean = true>(options?: Options<LoginLogoutData, ThrowOnError>): RequestResult<LoginLogoutResponses, unknown, ThrowOnError, 'data'> => (options?.client ?? client).post<LoginLogoutResponses, unknown, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/v1/login/logout',
    ...options
});

/**
 * Test Token
 *
 * Test access token
 */
export const loginTestToken = <ThrowOnError extends boolean = true>(options?: Options<LoginTestTokenData, ThrowOnError>): RequestResult<LoginTestTokenResponses, unknown, ThrowOnError, 'data'> => (options?.client ?? client).post<LoginTestTokenResponses, unknown, ThrowOnError, 'data'>({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/login/test-token',
    ...options
});

/**
 * Read Users
 *
 * Retrieve users.
 */
export const usersReadUsers = <ThrowOnError extends boolean = true>(options?: Options<UsersReadUsersData, ThrowOnError>): RequestResult<UsersReadUsersResponses, UsersReadUsersErrors, ThrowOnError, 'data'> => (options?.client ?? client).get<UsersReadUsersResponses, UsersReadUsersErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/',
    ...options
});

/**
 * Create User
 *
 * Create new user.
 */
export const usersCreateUser = <ThrowOnError extends boolean = true>(options: Options<UsersCreateUserData, ThrowOnError>): RequestResult<UsersCreateUserResponses, UsersCreateUserErrors, ThrowOnError, 'data'> => (options.client ?? client).post<UsersCreateUserResponses, UsersCreateUserErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete User Me
 *
 * Delete own user.
 */
export const usersDeleteUserMe = <ThrowOnError extends boolean = true>(options?: Options<UsersDeleteUserMeData, ThrowOnError>): RequestResult<UsersDeleteUserMeResponses, unknown, ThrowOnError, 'data'> => (options?.client ?? client).delete<UsersDeleteUserMeResponses, unknown, ThrowOnError, 'data'>({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/me',
    ...options
});

/**
 * Read User Me
 *
 * Get current user.
 */
export const usersReadUserMe = <ThrowOnError extends boolean = true>(options?: Options<UsersReadUserMeData, ThrowOnError>): RequestResult<UsersReadUserMeResponses, unknown, ThrowOnError, 'data'> => (options?.client ?? client).get<UsersReadUserMeResponses, unknown, ThrowOnError, 'data'>({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/me',
    ...options
});

/**
 * Update User Me
 *
 * Update own user.
 */
export const usersUpdateUserMe = <ThrowOnError extends boolean = true>(options: Options<UsersUpdateUserMeData, ThrowOnError>): RequestResult<UsersUpdateUserMeResponses, UsersUpdateUserMeErrors, ThrowOnError, 'data'> => (options.client ?? client).patch<UsersUpdateUserMeResponses, UsersUpdateUserMeErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/me',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update Password Me
 *
 * Update own password.
 */
export const usersUpdatePasswordMe = <ThrowOnError extends boolean = true>(options: Options<UsersUpdatePasswordMeData, ThrowOnError>): RequestResult<UsersUpdatePasswordMeResponses, UsersUpdatePasswordMeErrors, ThrowOnError, 'data'> => (options.client ?? client).patch<UsersUpdatePasswordMeResponses, UsersUpdatePasswordMeErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/me/password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Register User
 *
 * Create new user without the need to be logged in.
 */
export const usersRegisterUser = <ThrowOnError extends boolean = true>(options: Options<UsersRegisterUserData, ThrowOnError>): RequestResult<UsersRegisterUserResponses, UsersRegisterUserErrors, ThrowOnError, 'data'> => (options.client ?? client).post<UsersRegisterUserResponses, UsersRegisterUserErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/v1/users/signup',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete User
 *
 * Delete a user.
 */
export const usersDeleteUser = <ThrowOnError extends boolean = true>(options: Options<UsersDeleteUserData, ThrowOnError>): RequestResult<UsersDeleteUserResponses, UsersDeleteUserErrors, ThrowOnError, 'data'> => (options.client ?? client).delete<UsersDeleteUserResponses, UsersDeleteUserErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/{user_id}',
    ...options
});

/**
 * Read User By Id
 *
 * Get a specific user by id.
 */
export const usersReadUserById = <ThrowOnError extends boolean = true>(options: Options<UsersReadUserByIdData, ThrowOnError>): RequestResult<UsersReadUserByIdResponses, UsersReadUserByIdErrors, ThrowOnError, 'data'> => (options.client ?? client).get<UsersReadUserByIdResponses, UsersReadUserByIdErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/{user_id}',
    ...options
});

/**
 * Update User
 *
 * Update a user.
 */
export const usersUpdateUser = <ThrowOnError extends boolean = true>(options: Options<UsersUpdateUserData, ThrowOnError>): RequestResult<UsersUpdateUserResponses, UsersUpdateUserErrors, ThrowOnError, 'data'> => (options.client ?? client).patch<UsersUpdateUserResponses, UsersUpdateUserErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/{user_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Health Check
 */
export const utilsHealthCheck = <ThrowOnError extends boolean = true>(options?: Options<UtilsHealthCheckData, ThrowOnError>): RequestResult<UtilsHealthCheckResponses, unknown, ThrowOnError, 'data'> => (options?.client ?? client).get<UtilsHealthCheckResponses, unknown, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/v1/utils/health-check/',
    ...options
});

/**
 * Read Items
 *
 * Retrieve items.
 */
export const itemsReadItems = <ThrowOnError extends boolean = true>(options?: Options<ItemsReadItemsData, ThrowOnError>): RequestResult<ItemsReadItemsResponses, ItemsReadItemsErrors, ThrowOnError, 'data'> => (options?.client ?? client).get<ItemsReadItemsResponses, ItemsReadItemsErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/items/',
    ...options
});

/**
 * Create Item
 *
 * Create new item.
 */
export const itemsCreateItem = <ThrowOnError extends boolean = true>(options: Options<ItemsCreateItemData, ThrowOnError>): RequestResult<ItemsCreateItemResponses, ItemsCreateItemErrors, ThrowOnError, 'data'> => (options.client ?? client).post<ItemsCreateItemResponses, ItemsCreateItemErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/items/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Item
 *
 * Delete an item.
 */
export const itemsDeleteItem = <ThrowOnError extends boolean = true>(options: Options<ItemsDeleteItemData, ThrowOnError>): RequestResult<ItemsDeleteItemResponses, ItemsDeleteItemErrors, ThrowOnError, 'data'> => (options.client ?? client).delete<ItemsDeleteItemResponses, ItemsDeleteItemErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/items/{id}',
    ...options
});

/**
 * Read Item
 *
 * Get item by ID.
 */
export const itemsReadItem = <ThrowOnError extends boolean = true>(options: Options<ItemsReadItemData, ThrowOnError>): RequestResult<ItemsReadItemResponses, ItemsReadItemErrors, ThrowOnError, 'data'> => (options.client ?? client).get<ItemsReadItemResponses, ItemsReadItemErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/items/{id}',
    ...options
});

/**
 * Update Item
 *
 * Update an item.
 */
export const itemsUpdateItem = <ThrowOnError extends boolean = true>(options: Options<ItemsUpdateItemData, ThrowOnError>): RequestResult<ItemsUpdateItemResponses, ItemsUpdateItemErrors, ThrowOnError, 'data'> => (options.client ?? client).put<ItemsUpdateItemResponses, ItemsUpdateItemErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/items/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create User
 *
 * Create a new user.
 */
export const privateCreateUser = <ThrowOnError extends boolean = true>(options: Options<PrivateCreateUserData, ThrowOnError>): RequestResult<PrivateCreateUserResponses, PrivateCreateUserErrors, ThrowOnError, 'data'> => (options.client ?? client).post<PrivateCreateUserResponses, PrivateCreateUserErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/v1/private/users/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
